"""
Summary: Alert & Notification Formatter
Description: Memformat pesan ringkasan monitoring statistik untuk notifikasi WhatsApp/Telegram/Markdown.
"""
from typing import List, Dict, Any

def generate_daily_monitoring_alert(
    title: str,
    date_str: str,
    summary_stats: Dict[str, Any],
    top_critical_items: List[Dict[str, Any]] = None
) -> str:
    """
    Format pesan ringkasan monitoring harian pimpinan.
    """
    lines = [
        f"📊 *{title.upper()}*",
        f"📅 Tanggal: {date_str}",
        "──────────────────────────────",
        f"• Total Target: {summary_stats.get('total_target', 0)}",
        f"• Total Selesai: {summary_stats.get('total_completed', 0)}",
        f"• Progres: {summary_stats.get('progress_pct', 0.0):.2f}%",
        f"• Sisa Hari: {summary_stats.get('remaining_days', 0)} hari",
        "──────────────────────────────"
    ]
    
    if top_critical_items:
        lines.append("⚠️ *Daftar Perlu Perhatian / Intervensi:*")
        for idx, item in enumerate(top_critical_items[:5], 1):
            name = item.get("name", "Unknown")
            pct = item.get("progress_pct", 0.0)
            note = item.get("note", "")
            lines.append(f"{idx}. {name} - {pct:.1f}% ({note})")
            
    lines.append("──────────────────────────────")
    lines.append("🤖 _Generated by BPS Mempawah Windmill Automation Pipeline_")
    return "\n".join(lines)
